version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: lost_and_found
      POSTGRES_USER: yerassyl
      POSTGRES_PASSWORD: 12345era
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
      LC_ALL: en_US.utf8
      LANG: en_US.utf8
      LANGUAGE: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yerassyl -d lost_and_found"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - .:/code
    environment:
      DB_NAME: lost_and_found
      DB_USER: yerassyl
      DB_PASSWORD: 12345era
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    ports:
      - "80:80"
    depends_on:
      - web
      - minio



volumes:
  postgres_data:
  static_volume:
  minio_data:
